version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - bankmore-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - bankmore-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - bankmore-network

  sqlite-db:
    image: alpine:latest
    volumes:
      - ./database:/database
    command: sh -c "mkdir -p /database && touch /database/bankmore.db && tail -f /dev/null"
    networks:
      - bankmore-network

  account-api:
    build:
      context: .
      dockerfile: Dockerfile.account
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - redis
      - sqlite-db
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///database/bankmore.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - TRANSFER_FEE_AMOUNT=2.00
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    networks:
      - bankmore-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"

  transfer-api:
    build:
      context: .
      dockerfile: Dockerfile.transfer
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - redis
      - sqlite-db
      - account-api
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///database/bankmore.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - ACCOUNT_API_BASE_URL=http://account-api:8001
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    networks:
      - bankmore-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8002"

  fee-api:
    build:
      context: .
      dockerfile: Dockerfile.fee
    ports:
      - "8003:8003"
    depends_on:
      - kafka
      - redis
      - sqlite-db
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///database/bankmore.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - TRANSFER_FEE_AMOUNT=2.00
      - ACCOUNT_API_BASE_URL=http://account-api:8001
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    networks:
      - bankmore-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8003"

  fee-consumer:
    build:
      context: .
      dockerfile: Dockerfile.fee
    depends_on:
      - kafka
      - redis
      - sqlite-db
      - fee-api
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///database/bankmore.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - TRANSFER_FEE_AMOUNT=2.00
      - ACCOUNT_API_BASE_URL=http://account-api:8001
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    networks:
      - bankmore-network
    command: python manage.py consume_transfer_events

volumes:
  redis_data:

networks:
  bankmore-network:
    driver: bridge
